require("settings")
require("mappings")
require("colorschemes-config.dark2")
require("packer-config")
require("nvim-tree-config")
require('lsp-config.language-servers')
--require('lsp-config.efm')
--require('lsp-config.tsserver')
--require('lsp-config.eslint')
require('lsp-config.nvim-cmp')
require('lsp-config.null-ls')
--require('lualine-config')
require('barbar-config')
require('treesitter-config')
require('icons')
require('colorizer-config')
vim.cmd[[hi CursorLine term=bold cterm=bold guibg=Grey2]]
vim.cmd[[hi CursorLineNr term=bold cterm=bold guifg=orange guibg=Grey30]]
--au UIAttach * lua require('.gvimrc')
